print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/seanmacinnes/Documents/Game Dev II/Game/Igor Sucks/GameDev2/GravityWork/Assets/Models/Player/playerModels/character4.mb"`)
{		
	file -o "/Users/seanmacinnes/Documents/Game Dev II/Game/Igor Sucks/GameDev2/GravityWork/Assets/Models/Player/playerModels/character4.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/seanmacinnes/Documents/Game Dev II/Game/Igor Sucks/GameDev2/GravityWork/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/seanmacinnes/Documents/Game Dev II/Game/Igor Sucks/GameDev2/GravityWork/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/seanmacinnes/Documents/Game Dev II/Game/Igor Sucks/GameDev2/GravityWork/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
